# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    nginx.yaml                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: user42 <user42@student.42tokyo.jp>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/02 14:43:07 by user42            #+#    #+#              #
#    Updated: 2021/03/23 18:28:30 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: tkomatsu/nginx:latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep telegraf && pgrep nginx && pgrep sshd"]
          initialDelaySeconds: 10
          periodSeconds: 5
        env:
          - name: SERVICE
            value: nginx
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: ssh
    port: 22
