# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: user42 <user42@student.42tokyo.jp>         +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/17 08:56:07 by user42            #+#    #+#              #
#    Updated: 2021/03/17 09:44:20 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: tkomatsu/phpmyadmin:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: PMA_USER
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: db_user
          - name: PMA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: db_pass
          - name: PMA_HOST
            value: mysql-service

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - name: mmcc
    protocol: TCP
    port: 5000
    targetPort: 5000
