# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    phpmyadmin.yaml                                    :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tkomatsu <tkomatsu@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/24 18:48:23 by tkomatsu          #+#    #+#              #
#    Updated: 2021/03/24 18:48:24 by tkomatsu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      name: phpmyadmin
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: tkomatsu/phpmyadmin:latest
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command: ["/bin/sh", "-c", "pgrep telegraf && pgrep nginx && pgrep php-fpm"]
          initialDelaySeconds: 10
          periodSeconds: 5
        ports:
        - containerPort: 5000
        env:
          - name: SERVICE
            value: phpmyadmin
          - name: PMA_USER
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: db_user
          - name: PMA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: db_pass
          - name: PMA_HOST
            value: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  labels:
    app: phpmyadmin
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - name: mmcc
    protocol: TCP
    port: 5000
    targetPort: 5000
