# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    wordpress.yaml                                     :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: tkomatsu <tkomatsu@student.42tokyo.jp>     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/03/08 21:44:19 by tkomatsu          #+#    #+#              #
#    Updated: 2021/03/16 18:31:04 by user42           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      name: wordpress-pod
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: tkomatsu/wordpress:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: mysql_root_password
                optional: false
          - name: WORDPRESS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: db_name
                optional: false
          - name: WORDPRESS_DB_USER
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: db_user
                optional: false
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: db_pass
                optional: false
          - name: WORDPRESS_DB_HOST
            value: mysql-service:3306
          - name: WORDPRESS_DB_CHARSET
            value: utf8
          - name: WP_TITLE
            value: ft_services
          - name: WP_ADMIN
            value: admin
          - name: WP_ADMIN_PASS
            value: password
          - name: WP_ADMIN_MAIL
            value: admin@example.com
          - name: WP_USER1
            value: tony
          - name: WP_MAIL1
            value: tony.stark@example.com
          - name: WP_PASS1
            value: password
          - name: WP_USER2
            value: peter
          - name: WP_MAIL2
            value: peter.parker@example.com
          - name: WP_PASS2
            value: password
          - name: MINIKUBE_IP
            valueFrom:
              secretKeyRef:
                name: ft-secret
                key: minikube_ip
 
---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: ft_services
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - name: mmcc
    protocol: TCP
    port: 5050
    targetPort: 5050
